module.exports = {
	PLAYER_1_IDENTIFIER: 'PLAYER1',
	PLAYER_2_IDENTIFIER: 'PLAYER2',
	NO_WINNER_IDENTIFIER: 'NONE',
	MOVE_IDENTIFIER_PAPER: 'paper',
	MOVE_IDENTIFIER_ROCK: 'rock',
	MOVE_IDENTIFIER_SISSORS: 'sissors'
};
